export const BookedTable = [
  {
    show_name: "Bordello (Burlesque)",
    show_day: "Thursday",
    table_id: "seat_number_105_2",
    table_number: 105,
    table_price: 20,
    table_location: "Main Floor",
    table_booking_date: "02/27/2025",
    time_slot: "6:30 PM",
    time_Id: "time_1830",
  },
  {
    show_name: "Bordello (Burlesque)",
    show_day: "Thursday",
    table_id: "seat_number_101_1",
    table_number: 101,
    table_price: 20,
    table_location: "Main Floor",
    table_booking_date: "02/27/2025",
    time_slot: "6:30 PM",
    time_Id: "time_1830",
  },
  {
    show_name: "Bordello (Burlesque)",
    show_day: "Thursday",
    table_id: "seat_number_102_2",
    table_number: 102,
    table_price: 20,
    table_location: "Main Floor",
    table_booking_date: "02/27/2025",
    time_slot: "6:30 PM",
    time_Id: "time_1830",
  },

  {
    show_name: "Opus (Variety Show)",
    show_day: "Saturday",
    table_id: "seat_number_101_2",
    table_number: 101,
    table_price: 20,
    table_location: "Main Floor",
    table_booking_date: "03/29/2025",
    time_slot: "7:30 PM",
    time_Id: "time_1930",
  },
  {
    show_name: "Opus (Variety Show)",
    show_day: "Saturday",
    table_id: "seat_number_102_1",
    table_number: 102,
    table_price: 20,
    table_location: "Main Floor",
    table_booking_date: "03/29/2025",
    time_slot: "7:30 PM",
    time_Id: "time_1930",
  },
  {
    show_name: "Opus (Variety Show)",
    show_day: "Saturday",
    table_id: "seat_number_102_2",
    table_number: 102,
    table_price: 20,
    table_location: "Main Floor",
    table_booking_date: "03/29/2025",
    time_slot: "7:30 PM",
    time_Id: "time_1930",
  },
  ,
  {
    show_name: "Opus (Variety Show)",
    show_day: "Friday",
    table_id: "seat_number_311_2",
    table_number: 311,
    table_price: 50,
    table_location: "Mezzanine Floor",
    table_booking_date: "03/29/2025",
    time_slot: "6:30 PM",
    time_Id: "time_1830",
  },
  {
    show_name: "Opus (Variety Show)",
    show_day: "Friday",
    table_id: "seat_number_309_2",
    table_number: 309,
    table_price: 50,
    table_location: "Mezzanine Floor",
    table_booking_date: "03/29/2025",
    time_slot: "6:30 PM",
    time_Id: "time_1830",
  },
];
