export const FabrikaReservationTables = [
  {
    id: "A",
    table_number: "A",
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
    type: "per person",
  },
  {
    id: "B",
    table_number: "B",
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 1,
    table_number: 100,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 2,
    table_number: 101,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 3,
    table_number: 102,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 4,
    table_number: 103,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 5,
    table_number: 104,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 6,
    table_number: 105,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 7,
    table_number: 106,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 8,
    table_number: 107,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 9,
    table_number: 108,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 10,
    table_number: 109,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 11,
    table_number: 110,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 12,
    table_number: 111,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 13,
    table_number: 112,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 14,
    table_number: 113,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 15,
    table_number: 114,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 16,
    table_number: 115,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 17,
    table_number: 116,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 18,
    table_number: 117,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 19,
    table_number: 118,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 20,
    table_number: 119,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 21,
    table_number: 120,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 22,
    table_number: 121,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 23,
    table_number: 122,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 24,
    table_number: 123,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 25,
    table_number: 124,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 26,
    table_number: 125,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 27,
    table_number: 126,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 28,
    table_number: 127,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 29,
    table_number: 128,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 30,
    table_number: 129,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 31,
    table_number: 130,
    min_seat_requirment: 4,
    max_seat_requirment: 6,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 32,
    table_number: 131,
    min_seat_requirment: 4,
    max_seat_requirment: 6,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 33,
    table_number: 132,
    min_seat_requirment: 2,
    max_seat_requirment: 4,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 34,
    table_number: 133,
    min_seat_requirment: 2,
    max_seat_requirment: 4,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 35,
    table_number: 500,
    min_seat_requirment: 2,
    max_seat_requirment: 6,
    price: 50,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 36,
    table_number: 501,
    min_seat_requirment: 2,
    max_seat_requirment: 6,
    price: 50,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 37,
    table_number: 502,
    min_seat_requirment: 6,
    max_seat_requirment: 6,
    price: 50,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 38,
    table_number: 503,
    min_seat_requirment: 6,
    max_seat_requirment: 6,
    price: 50,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 39,
    table_number: 504,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 50,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 40,
    table_number: 505,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 50,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 41,
    table_number: 506,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 50,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 42,
    table_number: 200,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 43,
    table_number: 201,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 44,
    table_number: 202,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 45,
    table_number: 203,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 46,
    table_number: 204,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 47,
    table_number: 205,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 48,
    table_number: 206,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 49,
    table_number: 207,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 50,
    table_number: 208,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 51,
    table_number: 209,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 52,
    table_number: 210,
    min_seat_requirment: 2,
    max_seat_requirment: 4,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 53,
    table_number: 211,
    min_seat_requirment: 6,
    max_seat_requirment: 6,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 54,
    table_number: 212,
    min_seat_requirment: 6,
    max_seat_requirment: 6,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 55,
    table_number: 220,
    min_seat_requirment: 2,
    max_seat_requirment: 4,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 56,
    table_number: 221,
    min_seat_requirment: 6,
    max_seat_requirment: 6,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 57,
    table_number: 222,
    min_seat_requirment: 6,
    max_seat_requirment: 6,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 58,
    table_number: 230,
    min_seat_requirment: 4,
    max_seat_requirment: 6,
    price: 20,
    desc: "",
    image: "",
    location: "Main Floor",
  },
  {
    id: 59,
    table_number: 300,
    min_seat_requirment: 2,
    max_seat_requirment: 6,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 60,
    table_number: 301,
    min_seat_requirment: 2,
    max_seat_requirment: 6,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 61,
    table_number: 302,
    min_seat_requirment: 2,
    max_seat_requirment: 6,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 62,
    table_number: 303,
    min_seat_requirment: 2,
    max_seat_requirment: 6,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 63,
    table_number: 304,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 64,
    table_number: 305,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 65,
    table_number: 306,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 66,
    table_number: 307,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 67,
    table_number: 308,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 68,
    table_number: 309,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 69,
    table_number: 310,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 70,
    table_number: 311,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 71,
    table_number: 312,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 72,
    table_number: 313,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 73,
    table_number: 314,
    min_seat_requirment: 1,
    max_seat_requirment: 2,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 74,
    table_number: 315,
    min_seat_requirment: 2,
    max_seat_requirment: 6,
    price: "40 Per Person",
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 75,
    table_number: 316,
    min_seat_requirment: 2,
    max_seat_requirment: 6,
    price: "40 Per Person",
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 76,
    table_number: 317,
    min_seat_requirment: 2,
    max_seat_requirment: 6,
    price: "40 Per Person",
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 77,
    table_number: 400,
    min_seat_requirment: 2,
    max_seat_requirment: 6,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 78,
    table_number: 401,
    min_seat_requirment: 2,
    max_seat_requirment: 6,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 79,
    table_number: 402,
    min_seat_requirment: 2,
    max_seat_requirment: 6,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 80,
    table_number: 403,
    min_seat_requirment: 2,
    max_seat_requirment: 6,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 81,
    table_number: 600,
    min_seat_requirment: 6,
    max_seat_requirment: 8,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 82,
    table_number: 601,
    min_seat_requirment: 6,
    max_seat_requirment: 8,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 83,
    table_number: 602,
    min_seat_requirment: 6,
    max_seat_requirment: 8,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
  {
    id: 84,
    table_number: 603,
    min_seat_requirment: 6,
    max_seat_requirment: 8,
    price: 20,
    desc: "",
    image: "",
    location: "Mezzanine Floor",
  },
];

// const {
//   id,
//   table_number,
//   min_seat_requirment,
//   max_seat_requirment,
//   price,
//   desc,
//   image,
//   location,
// } = FabrikaReservationTables;
